name: Rust CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt upgrade
          sudo add-apt-repository ppa:gnome3-team/gnome3
          sudo apt update
          sudo apt install -y libgtk-4-dev libcairo2-dev libpango1.0-dev libglib2.0-dev

      - name: Install system dependencies (macOS only)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install pkg-config glib cairo pango fontconfig freetype harfbuzz gtk4

      - name: Setup MSYS2 and dependencies (Windows only)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: |
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-glib2
            mingw-w64-x86_64-gtk4
            mingw-w64-x86_64-cairo
            mingw-w64-x86_64-pango
            mingw-w64-x86_64-gdk-pixbuf2
            mingw-w64-x86_64-icu
            mingw-w64-x86_64-gobject-introspection

      - name: Add MSYS2 to PATH (Windows only)
        if: runner.os == 'Windows'
        run: echo "C:\\msys64\\mingw64\\bin" >> $GITHUB_PATH

      - name: Cache cargo registry and build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Set up Rust toolchain
        run: rustup toolchain install stable --profile minimal

      - name: Build and test workspace
        run: |
          cargo build --workspace --verbose
          cargo test --workspace --verbose
